spring:


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shop_reservation
    username: shop_reservation_user
    password: zerobase


  jpa: #?? ?? , ?? ??? ??? none, false -> ???, ???,sql ? ?? ?? ????? ??
    hibernate:
      ddl-auto: create
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hidden-method:
      filter:
        enabled: true